name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Smoke test imports
        run: |
          python - << 'EOF'
import argparse
from api_keys import load_api_keys
from scanners.hibp import check_breaches
from scanners.emailrep import check_emailrep
from scanners.breachdirectory import check_breachdirectory
from scanners.gravatar import check_gravatar
from scanners.whois_lookup import check_whois
from scanners.dns_check import check_dns
from scanners.abuseipdb import check_abuseipdb
from scanners.blacklist_check import check_blacklists
print("All modules import successfully")
EOF

      - name: Dry-run main
        run: |
          python main.py --email test@example.com || true

